app/connectify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base'), name='base'),
    path('blog/', include('blog.urls', namespace='blog'), name='blog'),
    path('account/', include('accounts.urls', namespace='accounts'), name='accounts'),
    path('user/', include('users.urls', namespace='users'), name='users'),
    path('room/', include('rooms.urls', namespace='rooms'), name='rooms'),
    path('api/', include('api.urls', namespace='api'), name='api'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

app/templates/app.html
{% extends 'base.html' %}
{% load static %}

{% block html_class %}layout-navbar-fixed layout-menu-fixed{% endblock html_class %}

{% block base_content %}
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            {% include 'partials/_menu.html' %}
            <!-- / Menu -->

            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->
                {% include 'partials/_navbar.html' %}
                <!-- / Navbar -->

                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->
                    {% block app_content %}{% endblock app_content %}
                    <!-- / Content -->

                    <!-- Footer -->
                    {% include 'partials/_footer.html' %}
                    <!-- / Footer -->

                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>

        <!-- Drag Target Area To SlideIn Menu On Small Screens -->
        <div class="drag-target"></div>
    </div>
    <!-- / Layout wrapper -->
{% endblock base_content %}

app/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en" class="dark-style {% block html_class %} {% endblock html_class %}" dir="ltr" data-theme="theme-default"
    data-assets-path="{% static 'assets/' %}" data-template="vertical-menu-template">

<head>
    <meta charset="utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>{% block title %} {% endblock title %} | {{ brand_name }} - {{ slogan }}</title>

    <meta name="description" content="{{ description }}">
    <meta name="author" content="Mohd Irfan">
    <meta name="robots" content="noindex, nofollow">


    <!-- CSS -->
    {% include 'partials/_styles.html' %}
    {% block page_styles %}{% endblock page_styles %}
</head>

<body>
    <!-- Page Container -->
    {% block base_content %}{% endblock base_content %}
    <!-- / Page Container -->

    <!-- Scripts -->
    {% include 'partials/_scripts.html' %}
    {% block page_scripts %}{% endblock page_scripts %}
</body>

</html>

app/templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error: 
                    {% else %}
                        {{ message.tags|title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

app/templates/partials/_breadcrumbs.html
{% load my_filters %}
{% with path=request.path|split_string:'/' %}
<h4 class="fw-medium mb-4">
    <span class="fw-light">
        <a class="fw-light" href="{% url 'base:index' %}">Home</a> / 
    </span>
    {{path.1|capfirst}}
    {% if path.2 %} / {{path.2|capfirst}}{% endif %}
    {% if path.3 %} / {{path.3|capfirst}}{% endif %}
</h4>
{% endwith %}

app/templates/partials/_footer.html
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl">
        <div class="footer-container d-flex align-items-center justify-content-between py-3 flex-md-row flex-column">
            <div class="mb-2 mb-md-0">{{ brand_name}} ©
                <script>
                    document.write(new Date().getFullYear());
                </script>
                , made with <span class="text-danger">❤️</span> by
                <a href="https://github.com/dev-mdirfan/" target="_blank" class="footer-link fw-medium">Md Irfan</a>
            </div>
            <div class="d-flex justify-content-start">
                <div class="dropdown-language dropdown me-2">
                    <!-- Language -->
                    <a class="btn btn-text-secondary rounded-pill btn-icon dropdown-toggle hide-arrow"
                        href="javascript:void(0);" data-bs-toggle="dropdown">
                        <i class="mdi mdi-translate mdi-24px mb-2"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li>
                            <a class="dropdown-item" href="javascript:void(0);" data-language="en">
                                <span class="align-middle">English</span>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="javascript:void(0);" data-language="fr">
                                <span class="align-middle">French</span>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="javascript:void(0);" data-language="de">
                                <span class="align-middle">German</span>
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="javascript:void(0);" data-language="pt">
                                <span class="align-middle">Portuguese</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <a href="https://github.com/dev-mdirfan/connectify/blob/master/LICENSE" class="footer-link me-4"
                    target="_blank">License</a>

                <a href="https://github.com/dev-mdirfan/connectify" target="_blank" class="footer-link me-4">Github</a>

                <a href="https://github.com/dev-mdirfan/" target="_blank"
                    class="footer-link d-none d-sm-inline-block">Support</a>
            </div>
        </div>
    </div>
</footer>

app/templates/partials/_menu.html
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a href="index.html" class="app-brand-link">
            <span class="app-brand-logo demo">
                <span style="color: var(--bs-primary)">
                    <svg width="268" height="150" viewBox="0 0 38 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M30.0944 2.22569C29.0511 0.444187 26.7508 -0.172113 24.9566 0.849138C23.1623 1.87039 22.5536 4.14247 23.5969 5.92397L30.5368 17.7743C31.5801 19.5558 33.8804 20.1721 35.6746 19.1509C37.4689 18.1296 38.0776 15.8575 37.0343 14.076L30.0944 2.22569Z"
                            fill="currentColor" />
                        <path
                            d="M30.171 2.22569C29.1277 0.444187 26.8274 -0.172113 25.0332 0.849138C23.2389 1.87039 22.6302 4.14247 23.6735 5.92397L30.6134 17.7743C31.6567 19.5558 33.957 20.1721 35.7512 19.1509C37.5455 18.1296 38.1542 15.8575 37.1109 14.076L30.171 2.22569Z"
                            fill="url(#paint0_linear_2989_100980)" fill-opacity="0.4" />
                        <path
                            d="M22.9676 2.22569C24.0109 0.444187 26.3112 -0.172113 28.1054 0.849138C29.8996 1.87039 30.5084 4.14247 29.4651 5.92397L22.5251 17.7743C21.4818 19.5558 19.1816 20.1721 17.3873 19.1509C15.5931 18.1296 14.9843 15.8575 16.0276 14.076L22.9676 2.22569Z"
                            fill="currentColor" />
                        <path
                            d="M14.9558 2.22569C13.9125 0.444187 11.6122 -0.172113 9.818 0.849138C8.02377 1.87039 7.41502 4.14247 8.45833 5.92397L15.3983 17.7743C16.4416 19.5558 18.7418 20.1721 20.5361 19.1509C22.3303 18.1296 22.9391 15.8575 21.8958 14.076L14.9558 2.22569Z"
                            fill="currentColor" />
                        <path
                            d="M14.9558 2.22569C13.9125 0.444187 11.6122 -0.172113 9.818 0.849138C8.02377 1.87039 7.41502 4.14247 8.45833 5.92397L15.3983 17.7743C16.4416 19.5558 18.7418 20.1721 20.5361 19.1509C22.3303 18.1296 22.9391 15.8575 21.8958 14.076L14.9558 2.22569Z"
                            fill="url(#paint1_linear_2989_100980)" fill-opacity="0.4" />
                        <path
                            d="M7.82901 2.22569C8.87231 0.444187 11.1726 -0.172113 12.9668 0.849138C14.7611 1.87039 15.3698 4.14247 14.3265 5.92397L7.38656 17.7743C6.34325 19.5558 4.04298 20.1721 2.24875 19.1509C0.454514 18.1296 -0.154233 15.8575 0.88907 14.076L7.82901 2.22569Z"
                            fill="currentColor" />
                        <defs>
                            <linearGradient id="paint0_linear_2989_100980" x1="5.36642" y1="0.849138" x2="10.532"
                                y2="24.104" gradientUnits="userSpaceOnUse">
                                <stop offset="0" stop-opacity="1" />
                                <stop offset="1" stop-opacity="0" />
                            </linearGradient>
                            <linearGradient id="paint1_linear_2989_100980" x1="5.19475" y1="0.849139" x2="10.3357"
                                y2="24.1155" gradientUnits="userSpaceOnUse">
                                <stop offset="0" stop-opacity="1" />
                                <stop offset="1" stop-opacity="0" />
                            </linearGradient>
                        </defs>
                    </svg>
                </span>
            </span>
            <span class="app-brand-text demo menu-text fw-bold ms-2">{{ brand_name }}</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
            <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M11.4854 4.88844C11.0081 4.41121 10.2344 4.41121 9.75715 4.88844L4.51028 10.1353C4.03297 10.6126 4.03297 11.3865 4.51028 11.8638L9.75715 17.1107C10.2344 17.5879 11.0081 17.5879 11.4854 17.1107C11.9626 16.6334 11.9626 15.8597 11.4854 15.3824L7.96672 11.8638C7.48942 11.3865 7.48942 10.6126 7.96672 10.1353L11.4854 6.61667C11.9626 6.13943 11.9626 5.36568 11.4854 4.88844Z"
                    fill="currentColor" fill-opacity="0.6" />
                <path
                    d="M15.8683 4.88844L10.6214 10.1353C10.1441 10.6126 10.1441 11.3865 10.6214 11.8638L15.8683 17.1107C16.3455 17.5879 17.1192 17.5879 17.5965 17.1107C18.0737 16.6334 18.0737 15.8597 17.5965 15.3824L14.0778 11.8638C13.6005 11.3865 13.6005 10.6126 14.0778 10.1353L17.5965 6.61667C18.0737 6.13943 18.0737 5.36568 17.5965 4.88844C17.1192 4.41121 16.3455 4.41121 15.8683 4.88844Z"
                    fill="currentColor" fill-opacity="0.38" />
            </svg>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Home -->
        <li class="menu-item
        {% if request.path == '/' %}
        active
        {% endif %}
        ">
            <a href="{% url 'base:index' %}" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-home-outline"></i>
                <div data-i18n="Home">Home</div>
            </a>
        </li>
        <!-- Blog -->
        <li class="menu-item
        {% if request.path == '/blog/' %}
        active
        {% endif %}
        ">
            <a href="{% url 'blog:blog' %}" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-post-outline"></i>
                <div data-i18n="Blog">Blog</div>
            </a>
        </li>
        <!-- Study Rooms -->
        <li class="menu-item
        {% if request.path == '/study-rooms/' %}
        active
        {% endif %}
        ">
            <a href="{% url 'base:index' %}" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-book-open-outline"></i>
                <div data-i18n="Study Rooms">Study Rooms</div>
                <div class="badge bg-primary ms-auto">New!</div>
            </a>
        </li>
        <!-- Dev Rooms -->
        <li class="menu-item
        {% if request.path == '/dev-rooms/' %}
        active
        {% endif %}
        ">
            <a href="{% url 'base:index' %}" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-code-tags-check"></i>
                <div data-i18n="Dev Rooms">Dev Rooms</div>
                <div class="badge bg-danger ms-auto">Hot!</div>
            </a>
        </li>


        <!-- Apps & Pages -->
        <li class="menu-header fw-light mt-4">
            <span class="menu-header-text">Settings</span>
        </li>
        {% if user.is_authenticated %}
        <!-- Profile -->
        <li class="menu-item
                {% if request.path == '/profile/' %}
                active
                {% endif %}
                ">
            <a href="{% url 'users:profile' user.profile.id %}" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-account-outline"></i>
                <div data-i18n="Profile">Profile</div>
            </a>
        </li>
        <!-- Chats -->
        <li class="menu-item
                {% if request.path == '/chat/' %}
                active
                {% endif %}
                ">
            <a href="" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-message-outline"></i>
                <div data-i18n="Chat">Chat</div>
            </a>
        </li>
        <!-- Settings -->
        <li class="menu-item
                {% if request.path == '/settings/' %}
                active
                {% endif %}
                ">
            <a href="" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-cog-outline"></i>
                <div data-i18n="Settings">Settings</div>
            </a>
        </li>
        <!-- Logout -->
        <li class="menu-item">
            <a href="{% url 'accounts:logout' %}" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-logout-variant"></i>
                <div data-i18n="Logout">Logout</div>
            </a>
        </li>
        {% else %}
        <!-- Dashboards -->
        <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons mdi mdi-home-outline"></i>
                <div data-i18n="Dashboards">Dashboards</div>
                <div class="badge bg-primary ms-auto">New!</div>
            </a>
            <ul class="menu-sub">
                <li class="menu-item">
                    <a href="dashboards-ecommerce.html" class="menu-link">
                        <div data-i18n="eCommerce">eCommerce</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="dashboards-crm.html" class="menu-link">
                        <div data-i18n="CRM">CRM</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="index.html" class="menu-link">
                        <div data-i18n="Analytics">Analytics</div>
                    </a>
                </li>
            </ul>
        </li>

        <!-- Layouts -->
        <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons mdi mdi-window-maximize"></i>
                <div data-i18n="Layouts">Layouts</div>
            </a>

            <ul class="menu-sub">
                <li class="menu-item">
                    <a href="layouts-collapsed-menu.html" class="menu-link">
                        <div data-i18n="Collapsed menu">Collapsed menu</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="layouts-content-navbar.html" class="menu-link">
                        <div data-i18n="Content navbar">Content navbar</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="layouts-content-navbar-with-sidebar.html" class="menu-link">
                        <div data-i18n="Content nav + Sidebar">Content nav + Sidebar</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="../horizontal-menu-template" class="menu-link" target="_blank">
                        <div data-i18n="Horizontal">Horizontal</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="layouts-without-menu.html" class="menu-link">
                        <div data-i18n="Without menu">Without menu</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="layouts-without-navbar.html" class="menu-link">
                        <div data-i18n="Without navbar">Without navbar</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="layouts-fluid.html" class="menu-link">
                        <div data-i18n="Fluid">Fluid</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="layouts-container.html" class="menu-link">
                        <div data-i18n="Container">Container</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="layouts-blank.html" class="menu-link">
                        <div data-i18n="Blank">Blank</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item">
            <a href="app-email.html" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-email-outline"></i>
                <div data-i18n="Email">Email</div>
            </a>
        </li>
        <li class="menu-item">
            <a href="app-calendar.html" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-calendar-blank-outline"></i>
                <div data-i18n="Calendar">Calendar</div>
            </a>
        </li>
        <li class="menu-item">
            <a href="app-kanban.html" class="menu-link">
                <i class="menu-icon tf-icons mdi mdi-view-grid-outline"></i>
                <div data-i18n="Kanban">Kanban</div>
            </a>
        </li>
        {% endif %}
    </ul>
</aside>

app/templates/partials/_scripts.html
{% load static %}
<!-- Core JS -->

<!-- build:js assets/vendor/js/core.js -->
<script src="{% static 'assets/vendor/libs/jquery/jquery.js' %}"></script>
<script src="{% static 'assets/vendor/libs/popper/popper.js' %}"></script>
<script src="{% static 'assets/vendor/js/bootstrap.js' %}"></script>
<script src="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
<script src="{% static 'assets/vendor/libs/node-waves/node-waves.js' %}"></script>
<script src="{% static 'assets/vendor/libs/hammer/hammer.js' %}"></script>
<script src="{% static 'assets/vendor/libs/i18n/i18n.js' %}"></script>
<script src="{% static 'assets/vendor/libs/typeahead-js/typeahead.js' %}">
</script>
<script src="{% static 'assets/vendor/js/menu.js' %}"></script>
<!-- endbuild -->

<!-- Main JS -->
<script src="{% static 'assets/js/main.js' %}"></script>

app/templates/partials/_styles.html
{% load static %}
<!-- Favicon -->
<link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon/favicon.ico' %}" />

<!-- Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />

<!-- Icons -->
<link rel="stylesheet" href="{% static 'assets/vendor/fonts/materialdesignicons.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendor/fonts/fontawesome.css' %}" />
<!-- Menu waves for no-customizer fix -->
<link rel="stylesheet" href="{% static 'assets/vendor/libs/node-waves/node-waves.css' %}" />

<!-- Core CSS -->
<link rel="stylesheet" href="{% static 'assets/vendor/css/rtl/core.css' %}" class="template-customizer-core-css" />
<link rel="stylesheet" href="{% static 'assets/vendor/css/rtl/theme-default.css' %}"
    class="template-customizer-theme-css" />
<link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />

<!-- Vendors CSS -->
<link rel="stylesheet" href="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendor/libs/typeahead-js/typeahead.css' %}" />

<!-- Page CSS -->

<!-- Helpers -->
<script src="{% static 'assets/vendor/js/helpers.js' %}"></script>

<!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
<!--? Template customizer: To hide customizer set displayCustomizer value false in config.js.  -->
<script src="{% static 'assets/vendor/js/template-customizer.js' %}"></script>
<!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
<script src="{% static 'assets/js/config.js' %}"></script>